name: Virtual Key
on: [push]
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Output
        id: output
        run: echo $(terraform output -raw private_key)

      - name: Write to file
        run: |-
          echo $(terraform output -raw private_key) >> terraform.pem
          ls -la
          chmod 400 terraform.pem
          cat terraform.pem

      - name: public ip
        run: echo $(terraform output -raw public_ip)

      - name: SSH into that bitch
        run: |
          ssh ec2-user@54.84.211.214 -i ./terraform.pem '
            echo "Hello from the EC2"
          '
