name: Virtual Key
on: [push]
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # - name: Terraform Format
      #   id: fmt
      #   run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      # - name: Terraform Validate
      #   id: validate
      #   run: terraform validate -no-color

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan -no-color

      # - name: Terraform Apply
      #   id: apply
      #   run: terraform apply -auto-approve

      - name: Write to file
        run: |-
          echo "$(terraform output -raw private_key)" >> terraform.pem
          echo "$(terraform output public_ip)" >> public_ip
          chmod 400 terraform.pem
          echo "$(cat ./terraform.pem)"
          echo "$(cat ./public_ip)"

      - name: SSH into
        run: |-
          echo "$(cat ./public_ip)"
          ssh -o StrictHostKeyChecking=no ec2-user@$(cat ./public_ip) -i ./terraform.pem
